dafny-lang/Dafny-VMC

Library/Random.dfy
=> Further simplify Bernoulli while loop

Library/Model/Monad.dfy
=> Details for Hurd Monad

Examples/Examples.dfy, Library/DRandom.dfy, Library/Model/Geometric.dfy, Library/Model/Helper.dfy, Library/Model/Monad.dfy, Library/Model/Uniform.dfy
=> Imperative sampler for Geometric(0.5) that satisfies the right spec

.gitignore, Examples/Examples.dfy, Library/DRandom.dfy
=> Implement Bernoulli(exp(-γ)) sampler (prerequisite for discrete Laplace)

Examples/Examples.dfy
=> Compute parameters in example file

Examples/Examples.dfy, Library/DRandom.dfy
=> Implement DiscreteLaplace(t/s)

Examples/Examples.dfy, Library/DRandom.dfy
=> Implement DiscreteGaussian(sigma)

Examples/Examples.dfy
=> Add Wolfram Alpha links for documentation

.gitignore, Library/Model/MeasureTheory.dfy, Library/Model/RandomNumberGenerator.dfy
=> Tweaks to measure theory formalization

Library/Model/Geometric.dfy
=> Fix verification timeout in Geometric

.gitignore, Library/Tests.dfy, README.md
=> Add statistical tests of implemented samplers

Examples/Examples.dfy, Library/DRandom.dfy, Library/Model/Model.dfy, Library/Model/Uniform.dfy
=> Uniform Power Of Two draft

src/Model/MeasureTheory.dfy
=> Define countable unions properly

docs/ExamplesExternUniform.dfy, docs/ExamplesFoundational.dfy
=> Fix examples

.github/workflows/test.yml, .github/workflows/verify.yml, test.sh, verify.sh
=> Split workflows into verification & tests

.github/workflows/build_cs.yml, .github/workflows/build_java.yml, .github/workflows/test_cs.yml, .github/workflows/test_java.yml, .github/workflows/verify.yml
=> Give better names to Gitub Actions jobs

Guidelines.md, src/Distributions/Bernoulli/Correctness.dfy, src/Distributions/BernoulliRational/Correctness.dfy, src/Distributions/Geometric/Correctness.dfy, src/Distributions/Uniform/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Math/Helper.dfy, src/Math/MeasureTheory.dfy
=> Naming + cleanup

Guidelines.md
Moving it to the Dafny guidelines.
=> Revert addition to guidelines

.github/workflows/format.yml, scripts/checkformat.sh, scripts/format.sh, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Math/Rationals.dfy
=> Check code formatting

audit.log, scripts/audit.sh
* Change to the audit script to filter out unimportant information
=> Improve auditor output

audit.log, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Implementation.dfy, src/Distributions/UniformPowerOfTwo/Model.dfy
=> Cleanup UniformPowerOfTwoModel

README.md
=> Minor bug in command line example in README.md

scripts/prep.sh
=> Upgrade to 4.3

audit.log, src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Distributions/BernoulliExpNeg/Implementation.dfy, src/Distributions/BernoulliExpNeg/Interface.dfy, src/Distributions/BernoulliExpNeg/Model.dfy, src/Distributions/Uniform/Implementation.dfy, src/Math/Exponential.dfy
=> Add model and state correctness property of BernoulliExpNeg

audit.log, scripts/verify.sh, src/Distributions/Uniform/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Model.dfy, src/Math/Helper.dfy
This reduces and limits the resource usage to 20M, which is still a lot, but at least it will prevent regressions.
=> Reduce and limit resource usage

src/Distributions/BernoulliExpNeg/Implementation.dfy, src/Distributions/Coin/Interface.dfy, src/Distributions/Uniform/Implementation.dfy, src/Math/MeasureTheory.dfy, src/ProbabilisticProgramming/WhileAndUntil.dfy
=> Commenting on assume statements

src/interop/java/DRandomCoin.java, src/interop/java/DRandomUniform.java
Changes RNG generation to be non-static for Java
=> Non-static RNG

audit.log, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Model.dfy, src/ProbabilisticProgramming/Monad.dfy, src/ProbabilisticProgramming/RandomSource.dfy
=> Move some items from Monad to RandomSource

audit.log, src/Distributions/Bernoulli/Correctness.dfy, src/Distributions/Bernoulli/Implementation.dfy, src/Distributions/Bernoulli/Model.dfy, src/Distributions/BernoulliExpNeg/Implementation.dfy, src/Distributions/BernoulliExpNeg/Model.dfy, src/Math/Helper.dfy
=> Prove correspondence between model and impl of BernoulliExpNeg

audit.log, src/Distributions/BernoulliExpNeg/Model.dfy
=> Fix comment

tests/Tests.dfy, tests/TestsExternUniformPowerOfTwo.dfy, tests/TestsFoundational.dfy
=> Add tests of Uniform with >64-bit arguments

audit.log, src/Distributions/BernoulliExpNeg/Equivalence.dfy, src/Distributions/BernoulliExpNeg/Implementation.dfy, src/Distributions/BernoulliExpNeg/Model.dfy
=> Simplify model & implementation of BernoulliExpNeg

src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Distributions/DiscreteGaussian/Implementation.dfy, src/Math/Rationals.dfy
=> Make functions on `Rational` members of the type

audit.log, src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Distributions/BernoulliExpNeg/Equivalence.dfy, src/Distributions/BernoulliExpNeg/Implementation.dfy, src/Distributions/BernoulliExpNeg/Model.dfy, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/ProbabilisticProgramming/Independence.dfy, src/ProbabilisticProgramming/Monad.dfy
=> Prove correctness of BernoulliExpNeg for γ > 1

audit.log, src/Distributions/Bernoulli/Correctness.dfy, src/Distributions/UniformPowerOfTwo/Correctness.dfy, src/Math/Analysis/Limits.dfy, src/Math/Analysis/Sequences.dfy, src/Math/Analysis/Series.dfy, src/Math/Measures.dfy, src/Math/NatArith.dfy
=> Define infinite series and prove basic properties

audit.log, src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Distributions/BernoulliExpNeg/Model.dfy, src/Math/Analysis/Limits.dfy, src/Math/Analysis/Sequences.dfy, src/Math/Measures.dfy, src/ProbabilisticProgramming/Independence.dfy, src/ProbabilisticProgramming/Loops.dfy
For now, this assumes measurability and independence of things.
=> Prove almost sure termination of BernoulliExpNeg

audit.log, src/Distributions/DiscreteLaplace/Equivalence.dfy, src/Distributions/DiscreteLaplace/Implementation.dfy, src/Distributions/DiscreteLaplace/Model.dfy
TODO:
- lower resource count
- proof of `SampleInnerLoopTerminatesAlmostSurely`
- proof of `SampleLoopTerminatesAlmostSurely`
=> DiscreteLaplace Full Equivalence

audit.log, src/Distributions/Bernoulli/Correctness.dfy, src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Math/Analysis/Limits.dfy, src/Math/Measures.dfy, src/Math/NatArith.dfy, src/Math/RealArithmetic.dfy, src/ProbabilisticProgramming/Loops.dfy
This PR `assume`s measurability of sets and independence of values of type `Hurd`. (Proving these is not hard, but tedious, so I'm deferring this to later.)
=> Prove correctness of the while loop in BernoulliExpNeg

audit.log, src/Distributions/BernoulliExpNeg/Correctness.dfy, src/Distributions/BernoulliExpNeg/Equivalence.dfy, src/Distributions/Uniform/Equivalence.dfy, src/Distributions/Uniform/Implementation.dfy, src/Distributions/Uniform/Model.dfy, src/ProbabilisticProgramming/Loops.dfy, src/Util/FisherYates/Correctness.dfy, src/Util/FisherYates/Model.dfy
=> Remove quantifier in postconditions

docs/java/BuildTest.java, src/interop/java/Full/Random.java
=> Java Supplier API

src/DafnyVMCTrait.dfy
=> Improved loop for parameters of Bernoulli expneg greater than 1

audit.log, src/DafnyVMCTrait.dfy, src/Distributions/Uniform/Correctness.dfy, src/Distributions/Uniform/Model.dfy, src/Util/FisherYates/Correctness.dfy, src/Util/FisherYates/Model.dfy
=> Axiomatise Uniform

docs/py/TestSamplers.py
=> Fix Python Tests

CITATION.cff, README.md
=> Citation and readme
