- tests/Tests.dfy
> Reduce spurious test failures by increasing threshold to 4 sigma

- Guidelines.md
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/Math/Helper.dfy
- src/Math/MeasureTheory.dfy
Used to take ~5min, now verifies in a few seconds
> Reduce Resource Usage for UniformPowerOfTwo correctness

- audit.log
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/ProbabilisticProgramming/Independence.dfy
I updated the definition of `IsIndepFn` in the process. The old definition seemed to be wrong.
> Independence proof for UniformPowerOfTwo

- audit.log
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Implementation.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
> Prove equivalence of implementation and model of UniformPowerOfTwo

- audit.log
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Implementation.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Implementation.dfy
- src/Distributions/UniformPowerOfTwo/Interface.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/Math/Helper.dfy
Fixes #79. It also
* changes the definition of the `UniformPowerOfTwo` model, which simplifies the correctness proof a lot.
* merges the even-odd case splits in the correctness proof
* removes an assume in the Uniform implementation
* cleans up `Helper.dfy`
> Simplify UniformPowerOfTwo

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Math/Helper.dfy
- src/ProbabilisticProgramming/WhileAndUntil.dfy
Also reduces the resource usage of `UniformFullCorrectness`.
> Clean up UniformCorrectness and WhileAndUntil

- audit.log
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Model.dfy
- src/Math/Helper.dfy
- src/ProbabilisticProgramming/WhileAndUntil.dfy
There's technically one `{:axiom}` left: for the external Uniform implementation. But we won't be able to get rid of that.
> Prove remaining {:axiom}s in Uniform

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Bernoulli/Model.dfy
- src/Distributions/BernoulliExpNeg/Model.dfy
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Implementation.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/ProbabilisticProgramming/Independence.dfy
- src/ProbabilisticProgramming/Loops.dfy
This is a step towards a proper definition of while loops.
Previously, we used a recursive definition, which needed an `assume false` for termination.
This PR changes it to (almost) Hurd's definition, but with a small modification because Dafny does not have an `arb` value like HOL.
> Define loops like Hurd and prove some of their properties

- .github/PULL_REQUEST_TEMPLATE.md
The current template is very noisy when looking at `git log` (because it shows the HTML comments) and a lot of it didn't apply to this project.
> Remove clutter from PR template

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Bernoulli/Implementation.dfy
- src/Distributions/Bernoulli/Interface.dfy
- src/Distributions/Bernoulli/Model.dfy
- src/Distributions/BernoulliExpNeg/Correctness.dfy
- src/Distributions/BernoulliExpNeg/Implementation.dfy
- src/Distributions/BernoulliExpNeg/Interface.dfy
- src/Distributions/Coin/Interface.dfy
- src/Distributions/Coin/Model.dfy
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Implementation.dfy
- src/Distributions/Uniform/Interface.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Implementation.dfy
- src/Distributions/UniformPowerOfTwo/Interface.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/ProbabilisticProgramming/Independence.dfy
- src/ProbabilisticProgramming/Loops.dfy
- src/ProbabilisticProgramming/Monad.dfy
This should make models and proofs easier to read. Concretely, this PR does the following:
* Introduce a type `datatype Result<A> = Result(value: A, rest: Rand.Bitstream)`
* Change the definition of `Hurd` from `type Hurd<A> = Rand.Bitstream -> (A, Rand.Bitstream)` to `type Hurd<A> = Rand.Bitstream -> Result<A>`
> Name the type and fields of the result of a monadic computation on a bitstream

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Bernoulli/Implementation.dfy
- src/Distributions/Bernoulli/Model.dfy
- src/Distributions/BernoulliExpNeg/Model.dfy
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Implementation.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/ProbabilisticProgramming/Loops.dfy
Reason: For while loops, the definition is not very helpful, it's better to rely on lemmas around it for proofs. When calling samplers, we should also not rely on their internals, but on their correctness properties. It also reduces resource usage.
As a concession, this PR also adds a postcondition for `While` to avoid having to call a lemma to handle the case of a while loop immediately exiting.
> Make samplers and `While` loops `opaque`

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Bernoulli/Model.dfy
- src/Distributions/BernoulliExpNeg/Correctness.dfy
- src/Distributions/BernoulliExpNeg/Model.dfy
- src/Distributions/Uniform/Correctness.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
- src/Math/Measures.dfy
- src/ProbabilisticProgramming/Independence.dfy
- src/ProbabilisticProgramming/Loops.dfy
- src/ProbabilisticProgramming/Monad.dfy
This PR changes the type of `Monad.Result<A>` from `Result(value: A, rest: Rand.Bitstream)` to `Diverging | Result(value: A, rest: Rand.Bitstream)`. In order to make it easier to work with, it also adds a few combinators for `Monad.Result` in order to avoid pattern matching everywhere.
The main benefit of this is that `While` loops can be properly defined without `assume false` and we can prove Hurd's theorem 38 (while loop unrolling) in Dafny. Another benefit is that we can reason about nontermination probabilities in Dafny via `Rand.prob(iset s | Sample(s).Diverging?)` for a probabilistic computation `Sample: Hurd<A>`.
For reasoning about the measurability of results, I also introduced some infrastructure to lift measure spaces on `A` to `Result<A>`, see `Monad.ResultEventSpace`, …
> Model nontermination explicitly ("partial Hurd monad")

- audit.log
- src/Distributions/BernoulliExpNeg/Equivalence.dfy
- src/Distributions/BernoulliExpNeg/Implementation.dfy
- src/Distributions/BernoulliExpNeg/Model.dfy
- src/Distributions/Uniform/Equivalence.dfy
- src/Distributions/Uniform/Implementation.dfy
- src/Distributions/Uniform/Model.dfy
- src/Distributions/UniformPowerOfTwo/Equivalence.dfy
- src/Distributions/UniformPowerOfTwo/Implementation.dfy
- src/Distributions/UniformPowerOfTwo/Model.dfy
Moving all the code that is referred to in `Implementation` to establish the equivalence between the imperative and functional model into a separate module `Equivalence`. The code in the new module should not be referred to by any other module than `Implementation`.
> Separate modules for equivalence proofs

- src/interop/java/DRandomUniform.java
> Java integer fix

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/Bernoulli/Model.dfy
- src/Distributions/BernoulliExpNeg/Equivalence.dfy
- src/Distributions/BernoulliExpNeg/Model.dfy
- src/Distributions/DiscreteLaplace/Implementation.dfy
- src/Distributions/DiscreteLaplace/Interface.dfy
- src/Distributions/Uniform/Interface.dfy
- src/ProbabilisticProgramming/Independence.dfy
- src/ProbabilisticProgramming/Loops.dfy
> Various cleanups

- audit.log
- src/Distributions/Bernoulli/Correctness.dfy
- src/Distributions/BernoulliExpNeg/Implementation.dfy
- src/Distributions/UniformPowerOfTwo/Correctness.dfy
- src/Math/Measures.dfy
- src/ProbabilisticProgramming/Monad.dfy
- src/ProbabilisticProgramming/RandomSource.dfy
> Remove sampleSpace variables

- audit.log
- src/Distributions/BernoulliExpNeg/Correctness.dfy
- src/Math/Analysis/Limits.dfy
- src/Math/Analysis/Series.dfy
- src/Math/Exponential.dfy
- src/Math/Measures.dfy
This finishes the "interesting" parts of the correctness proof of BernoulliExpNeg.
The following unproven assumptions are left in the proof:
- assuming measurability of some sets occurring in the proof
- assuming independence of `Hurd<A>` values
- assuming properties about the exponential functions and its series
> Finish* the correctness proof of BernoulliExpNeg

- audit.log
- src/Distributions/BernoulliExpNeg/Correctness.dfy
> Prove independence of BernoulliExpNeg.SampleLe1

- src/Util/FisherYates/Correctness.dfy
Matches the correctness specification we match against in `TestFisherYates` in `Tests.dfy`.
> Generalisation of Fisher-Yates Correctness

- tests/Tests.dfy
- tests/TestsRandom.dfy
> Fix and extend testing
